import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="container py-8">
          <header className="mb-8 flex items-center justify-between">
            <h1 className="text-2xl font-bold">Trip Planner</h1>
            <nav className="space-x-3">
              <a className="btn" href="/dashboard">Dashboard</a>
              <a className="btn" href="/submit">Submit</a>
            </nav>
          </header>
          {children}
        </div>
      </body>
    </html>
  );
}
